name = "logpush-bigquery"
main = "src/worker.js"
compatibility_date = "2023-08-25"

[vars]
# The necessary secrets are:
# - GOOGLE_APPLICATION_CREDENTIALS
# - DATASET_ID
# - TABLE_ID
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these